export const adviceDataEn = [
  { text: "Pay yourself first — save before you spend." },
  { text: "Track every expense, even small ones." },
  { text: "Create a monthly budget and follow it." },
  { text: "Spend less than you earn. Always." },
  { text: "Build an emergency fund with 3–6 months of expenses." },
  { text: "Avoid impulse buying — wait 24 hours before big purchases." },
  { text: "Separate needs from wants." },
  { text: "Don’t rely on one source of income." },
  { text: "Learn how compound interest works early." },
  { text: "Avoid high-interest debt whenever possible." },
  { text: "If you use credit, pay it off in full." },
  { text: "Set clear financial goals, short-term and long-term." },
  { text: "Invest in skills before investing in assets." },
  { text: "Start investing early, even with small amounts." },
  { text: "Never invest money you can’t afford to lose." },
  { text: "Diversify — don’t put all your money in one place." },
  { text: "Understand what you invest in." },
  { text: "Keep emotions out of financial decisions." },
  { text: "Live below your means, not at your limit." },
  { text: "Learn basic personal finance and economics." },
  { text: "Automate savings and investments when possible." },
  { text: "Avoid lifestyle inflation as income grows." },
  { text: "Keep finances simple — complexity hides mistakes." },
  { text: "Protect your assets and financial data." },
  { text: "Compare prices before expensive purchases." },
  { text: "Don’t chase fast money — think long term." },
  { text: "Use debt only if it creates value." },
  { text: "Review your finances regularly." },
  { text: "Learn from financial mistakes." },
  { text: "Discipline and time matter more than talent with money." }
];
